theme: jekyll-theme-cayman
title: [Cache Coherence Protocols Analyzer]
description: [An analyzer for Cache Coherence Protocols under varying workloads.<br>
              Kshitiz Dange (kdange)  |  Yash Tibrewal (ytibrewa)]

proposal_page: proposal-page
authors_page: authors-page
checkpoint_page: checkpoint-page
final-report_page: final-report
